### ISSUE TITLE
Integration in a complete dungeon and dragons app

### ISSUE THREAD

**Issue by sbordeyne** [jamis/dnd-npc#1]
I'm designing a software to play OD&D online, and wanted a NPC generator inside it. How do you think I can import your work inside my project?

It's written in python, http://www.github.com/dogeek/dndapp

**Comment by jamis** [comment]
You have a couple of options, I think. You could either build a command-line version of the NPC generator, and then shell out to it from within your python script to generate the characters, or you could write Python bindings for it. The external API of the generator ought to be fairly clean, so bindings wouldn't be too hard (though it's been a very long time since I've written Python bindings for anything, so I could be very wrong about the amount of work, there!).

Good luck!
